name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.jobs
        uses: actions/setup-node@v4
        with:
          node-version: 22.15

      - name: Instalar dependências
        run: npm i

      - name: Rodar os testes
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: success()

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Testar login no Docker
        run: docker info

      - name: Build da imagem de produção
        run: docker build -f Dockerfile.prod -t frontend:latest .

      - name: Deploy para Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: eImjxQMp73zPg4p6r99FIXLx
          vercel-args: "--prod"
          vercel-org-id: lavinia-monteiros-projects
          vercel-project-id: prj_uuNlqkMFF4zMhTorgDntxUV6hbOC